### ISSUE TITLE
simple stacktrace

### ISSUE THREAD

**Issue by luandrea** [luandrea/testrepo-github-app#18]
java.lang.RuntimeException: Failed to load XML schemas: [classpath:pdp.xsd]
at org.ow2.authzforce.core.pdp.impl.SchemaHandler.createSchema(SchemaHandler.java:541)
at org.ow2.authzforce.core.pdp.impl.PdpModelHandler.(PdpModelHandler.java:159)
at org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration.getInstance(PdpEngineConfiguration.java:682)
at org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration.getInstance(PdpEngineConfiguration.java:699)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)

**Comment by luandrea** [comment]
Start Botsing on artifact org.ow2.authzforce:authzforce-ce-core-pdp-testutils:13.3.1 to reproduce the stacktrace in the issue.

**Comment by luandrea** [comment]
Error executing Botsing

**Comment by luandrea** [comment]
I need to install the 1.0.6-SNAPSHOT version first...
