### ISSUE TITLE
Dirty stacktrace

### ISSUE THREAD

**Issue by luandrea** [luandrea/testrepo-github-app#20]
java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pdp' defined in URL [file:/home/gibello/STAMP/STAMP-project/authzforce/core/pdp-testutils/target/test-classes/org/ow2/authzforce/core/pdp/testutil/test/pep/cxf/cxf-doubleit-service.xml]: Cannot create inner bean 'org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration#3aefe5e5' of type [org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration#3aefe5e5' defined in URL [file:/home/gibello/STAMP/STAMP-project/authzforce/core/pdp-testutils/target/test-classes/org/ow2/authzforce/core/pdp/testutil/test/pep/cxf/cxf-doubleit-service.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration]: Factory method 'getInstance' threw exception; nested exception is java.lang.RuntimeException: Failed to load XML schemas: [classpath:pdp.xsd]
	at org.apache.cxf.bus.spring.SpringBusFactory.createBus(SpringBusFactory.java:193)
	at org.apache.cxf.bus.spring.SpringBusFactory.createBus(SpringBusFactory.java:185)
	at org.apache.cxf.bus.spring.SpringBusFactory.createBus(SpringBusFactory.java:175)
	at org.ow2.authzforce.core.pdp.testutil.test.pep.cxf.Server.run(Server.java:39)
	at org.apache.cxf.testutil.common.AbstractTestServerBase.startInProcess(AbstractTestServerBase.java:47)
	at org.apache.cxf.testutil.common.ServerLauncher.launchServer(ServerLauncher.java:197)
	at org.apache.cxf.testutil.common.AbstractClientServerTestBase.launchServer(AbstractClientServerTestBase.java:90)
	at org.ow2.authzforce.core.pdp.testutil.test.pep.cxf.EmbeddedPdpBasedAuthzInterceptorTest.startServers(EmbeddedPdpBasedAuthzInterceptorTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at eu.stamp_project.testrunner.runner.JUnit4Runner.run(JUnit4Runner.java:63)
	at eu.stamp_project.testrunner.runner.JUnit4Runner.main(JUnit4Runner.java:27)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'pdp' defined in URL [file:/home/gibello/STAMP/STAMP-project/authzforce/core/pdp-testutils/target/test-classes/org/ow2/authzforce/core/pdp/testutil/test/pep/cxf/cxf-doubleit-service.xml]: Cannot create inner bean 'org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration#3aefe5e5' of type [org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration] while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration#3aefe5e5' defined in URL [file:/home/gibello/STAMP/STAMP-project/authzforce/core/pdp-testutils/target/test-classes/org/ow2/authzforce/core/pdp/testutil/test/pep/cxf/cxf-doubleit-service.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration]: Factory method 'getInstance' threw exception; nested exception is java.lang.RuntimeException: Failed to load XML schemas: [classpath:pdp.xsd]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:122)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveConstructorArguments(ConstructorResolver.java:648)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:145)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1198)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1100)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:312)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:308)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.apache.cxf.bus.spring.BusApplicationContext$2.run(BusApplicationContext.java:133)
	at org.apache.cxf.bus.spring.BusApplicationContext$2.run(BusApplicationContext.java:131)
	at org.apache.cxf.bus.spring.BusApplicationContext.<init>(BusApplicationContext.java:131)
	at org.apache.cxf.bus.spring.SpringBusFactory.createAppContext(SpringBusFactory.java:198)
	at org.apache.cxf.bus.spring.SpringBusFactory.createBus(SpringBusFactory.java:190)
	... 27 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration#3aefe5e5' defined in URL [file:/home/gibello/STAMP/STAMP-project/authzforce/core/pdp-testutils/target/test-classes/org/ow2/authzforce/core/pdp/testutil/test/pep/cxf/cxf-doubleit-service.xml]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration]: Factory method 'getInstance' threw exception; nested exception is java.lang.RuntimeException: Failed to load XML schemas: [classpath:pdp.xsd]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1178)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1072)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:481)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:299)
	... 47 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration]: Factory method 'getInstance' threw exception; nested exception is java.lang.RuntimeException: Failed to load XML schemas: [classpath:pdp.xsd]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 52 more
Caused by: java.lang.RuntimeException: Failed to load XML schemas: [classpath:pdp.xsd]
	at org.ow2.authzforce.core.pdp.impl.SchemaHandler.createSchema(SchemaHandler.java:541)
	at org.ow2.authzforce.core.pdp.impl.PdpModelHandler.<init>(PdpModelHandler.java:159)
	at org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration.getInstance(PdpEngineConfiguration.java:682)
	at org.ow2.authzforce.core.pdp.impl.PdpEngineConfiguration.getInstance(PdpEngineConfiguration.java:699)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 53 more

**Comment by luandrea** [comment]
Start Botsing on artifact org.ow2.authzforce:authzforce-ce-core-pdp-testutils:13.3.1 to reproduce the stacktrace in the issue.

**Comment by luandrea** [comment]
Error executing Botsing
